"""reiniciar migraciones

Revision ID: 5c34105421db
Revises: 
Create Date: 2025-06-04 14:36:56.982404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c34105421db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('comensales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reservations')
    op.drop_column('user', 'date')
    op.drop_column('user', 'hora')
    op.drop_column('user', 'comensales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comensales', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('reservations',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locales_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['locales_id'], ['locales.id'], name='reservations_locales_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='reservations_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'locales_id', name='reservations_pkey')
    )
    op.drop_table('reserva')
    # ### end Alembic commands ###
